####################################################################################
# lm_docker_strategy == from_registry
####################################################################################

- name: Create Docker Image Registry values file
  template:
    src: "docker-registry-values.yml"
    dest: "{{ lm_installer_dir }}/docker-registry-values.yml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Create Docker Registry values file inclusion property
  set_fact:
    docker_registry_values_path: "{{ lm_installer_dir }}/docker-registry-values.yml"
